
library(rgdal)
library(sp)
library(data.table)

### Load stock boundary metadata generated by Chris Free
### For US East Coast, most of these were derived from the NOAA EFH GIS Data Inventory
### Might be better do get list of statistical areas from stock assessment (which I've already done for half of the E Coast RAM stocks)
stockbound.meta <- as.data.table(read.csv("Data/ramldb_v3.8_stock_boundary_table_v2_formatted.csv"))

### Limit to stocks in US and Canada
stockbound.NAM <- stockbound.meta[country %in% c("USA", "Canada")]
stockbound.NAM[,"assessid":=factor(assessid)]
stockbound.NAM[,"stockid":=factor(stockid)]


### Load haul locations from Jim
hauls <- readRDS("Data/hauls_jm.rds")

### If lon < -180, assign to 180 + (lon + 180)
hauls[,"lon.adj":=ifelse(lon < -180, 180 + (lon +180), lon)]
coordinates(hauls) <- ~cbind(hauls$lon.adj, hauls$lat)



### Extract haul locations from stock boundary shapefile
hauls.stock2 <- stockbound.NAM[,j={
  print(assessid)
  t.dt <- .SD
  shape <- readOGR("Data/ramldb_boundaries/", as.character(assessid))
  hauls.temp <- copy(hauls)
  
 proj4string(hauls.temp) <- proj4string(shape)
 
 hauls_st <- over(shape, hauls.temp, returnList=T)[[1]]
 list(haulid=hauls_st$haulid, region=hauls_st$region, lat=hauls_st$lat, lon=hauls_st$lon, spp=unique(t.dt$species))
}, by=list(assessid, stockid)]

saveRDS(hauls.stock2, "Output/hauls_ram.rds")

### Only really inshore GOM for winter flounder? (these were uploaded by Chris from EFH)
### Should include stat area 511-515
shape.wfgom <- readOGR("Data/ramldb_boundaries", as.character(stockbound.Ecoast[stockid=="WINFLOUND5Y"]$assessid))
