### Objective: Estimate landings by latitude bin by combining the following sources:
# (1) statarea catch database from Sean Lucey 1960-2014
# (2) Distribution of harvest latitude landed in a state for each  stock estimated from VTR 1996-2015
# (3) NOAA Annual Landings by State 1950-2014
# (4) Year that a state reported to statarea catch database
# (5) % of landings in each stock by state

# Method: 
# Assign landings for a state to a stock based on % landed in each stock
# Assign latitude density from VTR distribution for the stock * total annual landings in the state. 
# Add to statarea catch database for states not reporting in years not reporting
# Sum landings by latitude bin (1 degree) across the two catch sources


library(data.table)
library(rgdal)
library(trawlData)
library(maptools)
library(sp)

### Load information about stat stock areas
stat_stock <- as.data.table(read.csv("Data/StatusFishResStatAreas.csv"))

### Load geographic information about the statistical areas
statarea_km2 <- as.data.table(readRDS("Data/stat_area_areas.rds")) #area and coordinates of each stat area
plot(lat ~ lon, statarea_km2[stat_area>500 & !(stat_area %in% c(640,650,660,670,680))])

### Load landings by statistical area database from Sean Lucey
load("Data/comland_by_statarea.RData", verbose=T) #Data sent to me by Sean Lucey and Mike Fogarty on 5/9/16
load("Data/Species_codes_NEW.RData", verbose=T) #New file sent to me by Sean Lucey on 12/6/2016


head(spp.land) # name of first data file
head(spp) #name of second data file

### Merge spp.land with areas and coordinates of each statistical area
spp.land <- merge(spp.land, statarea_km2, by.x="AREA", by.y="stat_area")

### Calculate landings in terms of kg/km2 by dividing by km2 of statarea (1 metric ton= 1000kg)
spp.land[,"kg_km2":=1000*SPPLIVMT/area_km2]
# 

### Total landings by species in statarea database
total.lnd <- spp.land[,list(SPPLIVMT=sum(SPPLIVMT)), by=list(NESPP3)]



# ========================
# = Cleaning species key =
# ========================
species <- as.data.table(spp)



### Convert sci name out of all capitals and get rid of white space on a few flounders
species[,"spp.temp":= ifelse(SCINAME=="LIMANDA FERRUGINEA ", "limanda ferruginea",
                             ifelse(SCINAME=="PSEUDOPLEURONECTES AMERICANUS ", "pseudopleuronectes americanus", tolower(SCINAME)))]
species[,"spp":= paste0(toupper(substr(spp.temp,1,1)),substr(spp.temp, 2, nchar(spp.temp)))]
species[,"spp.temp":=NULL]

### Explore Duplicates in species key
dup.spp <- species[duplicated(species$NESPP3)] #589 species with NESPP3= NA

### Get rid of duplicates in species key
species2 <- species[!duplicated(NESPP3)]



setorder(species2, spp)




# ====================================
# = Get spp info into landing database =
# ====================================
### Merge landings data with species metadata
spp.land2 <- merge(spp.land, species2, by="NESPP3", all.x=T)
spp.land2[,"year":=YEAR]


### Restrict to RAM stocks and landing within the statistical areas defined for each stock
spp.land.ram <- merge(spp.land2, stat_stock, by.x=c("spp", "AREA"), by.y=c("spp", "StatArea"))



# ### Total Landings  by year in all statistical areas (used in later merge)
# total.land.catch <- spp.land2[,list(SPPLIVMT=sum(SPPLIVMT, na.rm=T)), by=list(NESPP3, year, COMNAME, SCINAME, spp)]
# setorder(total.land.catch, year)
# 
# 
# spp.wland <- spp.land2[,list(spp=unique(spp))]




# =======================
# = Sum landings by latitude by species by year from statarea catch database=
# =======================
### Use coordinates for statistical area to generate latitude
spp.land.lat <- spp.land.ram[,
                          list(tl_mt=sum(SPPLIVMT, na.rm=T), source="catch_dat"), by=list(spp, RAM_stockid, year, lat)]

setorder(spp.land.lat, year)

# statarea.landNEUS <- spp.land.lat[,list(total_statland=sum(tl_mt)), by=list(spp, year)]
# setorder(statarea.landNEUS, year)

# =======================
# = Years each state came into statarea Catch Dataset =
# =======================
### From email with Geret DePiper (NEFSC) on 4/2/18
### Exclude North Carolina
year.catch.include <- data.table(year.catch=c(1960, 1960, 1960, 1978, 1980, 1982, 1982, 1988, 1989, 1989),
                                 state=c("Massachusetts", "Maine", "Rhode Island", "New Jersey", "Virginia",
                                         "Maryland", "New Hampshire", "New York", "Delaware", "Connecticut"),
                                 state.abb=c("ma", "me", "ri", "nj", "va", "md", "nh", "ny", "de", "ct"))

### Prior to these years, assign noaa annual landings to latitude based on density fits to VTR period (1996-2015) for trips landed in the state for each stock
### One density curve for each stock generated pooling all years of data in VTR
### Generated by DistVTR_Lat_Stock.R
stock.state <- readRDS("Output/vtr_main_stock.rds")
lat.state <- readRDS("Output/land.lat.state.vtr.ramstock.rds")


lat.state[,"state.abb":=state]
lat.state[,"state":=NULL]
# area under density curve sums to 1 (ie sum(width of interval in x *y)) but sum(y)=30.08824 in this case so divide by this when divvying out to sum to 1
lat.state[,"total.dens":=sum(dens.qty), by=list(state.abb, sppcode, RAM_stockid)] 

png("Figures/BSB_density.png", height=7, width=7, units="in", res=300)
par(mfrow=c(3,3))
lat.state[state.abb!="me" & state.abb!="nc" & sppcode=="BSB",j={
  plot(dens.qty ~ lat, type="l", main=state.abb)
}, by=list(state.abb)]
dev.off()


### Load annual landings by state
noaa.ann <- as.data.table(read.csv("Data/noaa_landings_data_annual.csv"))

### Sum across taxa_format (for some species there are two records e.g. Callinectes sapidus one for soft, other regular)
### Eastern oyster, a mistake to have two records (take mean in that case)
### So if the poundage is the same, take mean, if the poundage is different (indicating more than 1 type of a single species), sum
noaa.ann.summ <- noaa.ann[,
                          list(tl_lb=ifelse(length(unique(tl_lb))==1, mean(tl_lb, na.rm=T),sum(tl_lb, na.rm=T)), 
                               tl_mt=ifelse(length(unique(tl_mt))==1, mean(tl_mt, na.rm=T), sum(tl_mt, na.rm=T)),
                               num.rec=.N), by=list(state, taxa_format, year)]



### Match with species names for noaa commercial landings
noaa_top_matched <- as.data.table(read.csv("Data/noaa_top_spp_matched.csv"))
### Get rid of duplicate entries for species with more than one NESPP3 code
noaa_top_matched2 <- noaa_top_matched[,list(mean_land_lb=mean(mean_land_lb)), by=list(taxa_format, spp)]

### Merge noaa annual landings with species names
noaa.ann2 <- merge(noaa.ann.summ, noaa_top_matched2[!(is.na(spp))], by=c("taxa_format"))

### Merge noaa annual landings with information on when catch was included in the statarea catch database (this also restricts to NE states)
noaa.ann3 <- merge(noaa.ann2, year.catch.include, by=c("state"))

# ### Calculate total landings based on NOAA annual landings by state for the Northeast states in our analysis  
# noaa.ann.total <- noaa.ann3[,list(total.land.mt=sum(tl_mt)), by=list(spp, year)]
# setorder(noaa.ann.total, year)
# 
# ### In comparison with statarea database, well matched for northern species like cod
# plot(total.land.mt ~ year, noaa.ann.total[spp=="Gadus morhua"], col="black", type="o")
# points(total_statland ~ year, statarea.landNEUS[spp=="Gadus morhua"], col="blue", type="o")
# ### Southern species like BSB, statarea database missing a lot in beginning of time series (as expected)
# plot(total.land.mt ~ year, noaa.ann.total[spp=="Centropristis striata"], col="black", type="o")
# points(total_statland ~ year, statarea.landNEUS[spp=="Centropristis striata"], col="blue", type="o")
# 

### Assign state-level landings to a stock based on % of each stock landed by a state in VTR
noaa.ann.stock <- merge(noaa.ann3, stock.state, by.x=c("spp", "state.abb"), by.y=c("spp", "state"))
noaa.ann.stock[,"tl_lb_stock":=tl_lb * frac.stock]


### Assign state-level landings to a latitude based on density of latitude from VTR for each stock, 
### only for years prior to the state reporting to the statarea database
noaa.lat.est <- noaa.ann.stock[year>=1960 & year<year.catch,j={
  print(paste0(state,year, spp, RAM_stockid))
  t.dt <-.SD
  l.noaa <- length(t.dt$tl_lb_stock)
  lat.dist <- lat.state[state.abb %in% t.dt$state.abb & RAM_stockid %in% t.dt$RAM_stockid]
  lat.dist[,"tl_lb_state":= t.dt$tl_lb_stock]
  lat.dist[,"tl_lb_est":=(dens.qty/total.dens) * tl_lb_state]
  lat.dist[,"tl_mt_est":=tl_lb_est * 0.000453592] #convert from lbs to metric tons
  lat.dist[,"num.catch.rec":=l.noaa]
}, by=list(state, year, spp, sppcode, RAM_stockid), .SDcols=colnames(noaa.ann.stock)]

dev.new()
par(mfrow=c(2,3))
noaa.lat.est[sppcode=="BSB",j={
  plot(tl_mt_est ~ lat, .SD, type="l", main=state)
}, by=list(state)]

### Sum estimated landings across states by lat
noaa.lat.est.sum <- noaa.lat.est[,list(tl_mt=sum(tl_mt_est, na.rm=T), source="noaa_ann"), 
                                 by=list(spp, RAM_stockid, year, lat)]

plot(tl_mt ~ lat, noaa.lat.est.sum[spp=="Centropristis striata" & year==1970])

### Add rows for estimated landings by latitude to the catch by latitudes from statarea catch database
total.land.est <- rbind(noaa.lat.est.sum, spp.land.lat)
setorder(total.land.est, spp, year)

### Assign to latitude bin
lat.brks <- seq(30,46, by=1)
lat.labs <- seq(30.5, 45.5, by=1) #these correspond approximately to the statarea coordinates (particularly in MAB where regular grid)

total.land.est[,"lat.bin":=cut(lat, breaks=lat.brks, labels=lat.labs)]

### Sum Landings by latbin including both those estimated from noaa annual landings and that from the statarea catch database
total.land.latbin <- total.land.est[,list(tl_mt=sum(tl_mt, na.rm=T)),
                                     by=list(RAM_stockid, spp, year, lat.bin)]

setorder(total.land.latbin, spp, year)



# =======================
# = Centroid of Estimated Landings =
# =======================
### Centroid of estimated landings combining the two data sources
cent.land.est <- total.land.est[year>=1968,list(cent.lat=weighted.mean(lat, w=tl_mt),
                                                cent.lat.cd =weighted.mean(lat[source=="catch_dat"], w=tl_mt[source=="catch_dat"]),
                                                total.land.mt=sum(tl_mt)), by=list(spp, RAM_stockid, year)]
setorder(cent.land.est, year)

# ### Centroid of only the statarea catch database
# cent.land.catchdat <- total.land.est[year>=1968 & source=="catch_dat",
#                                      list(cent.lat=weighted.mean(lat, w=tl_mt),
#                                           total.land.mt=sum(tl_mt)), by=list(spp, RAM_stockid, year)]
# setorder(cent.land.catchdat, year)


spp.S <- c("Centropristis striata", "Stenotomus chrysops", "Cynoscion regalis", "Paralichthys dentatus")
spp.N <- c("Gadus morhua", "Merluccius bilinearis", "Urophycis chuss", "Urophycis tenuis")

png("Figures/CatchReconsSspp.png", height=8, width=8, units="in", res=300)
par(mfrow=c(2,2), mar=c(4,4,2,2))
cent.land.est[spp%in%spp.S, j={
  plot(cent.lat ~ year, .SD, col="red", type="l", ylim=c(38,43),
       main=paste0(spp, "_", RAM_stockid), ylab="Landings Centroid (Latitude)")
  points(cent.lat.cd ~ year, .SD, type="l")
  legend("topright", legend=c("CatchDat", "CatchwNOAAest"), col=c("black", "red"), lty=1, bty="n")
  #list(spp=spp)
}, by=list(spp, RAM_stockid)]
dev.off()

png("Figures/CatchReconsNspp.png", height=6, width=8, units="in", res=300)
par(mfrow=c(2,3), mar=c(4,4,2,2))
cent.land.est[spp%in%spp.N, j={
  plot(cent.lat ~ year, .SD, col="red", type="l", ylim=c(38,43),
       main=paste0(spp, "_", RAM_stockid), ylab="Landings Centroid (Latitude)")
  points(cent.lat.cd ~ year, .SD, type="l")
  legend("bottomright", legend=c("CatchDat", "CatchwNOAAest"), col=c("black", "red"), lty=1, bty="n")
  #list(spp=spp)
}, by=list(spp, RAM_stockid)]
dev.off()








### Years with catch by stock
yrs.catch.stock <- total.land.latbin[,list(min.yr=min(year), max.yr=max(year)), by=list(spp, RAM_stockid)]
yrs.catch.stock[min.yr<=1970] #41 stocks (plus 2 not in RAM= Loligo and Red Hake),  only skates=little and winter


### Save final landings by latitude data output
saveRDS(total.land.latbin[RAM_stockid %in% yrs.catch.stock[min.yr<=1970]$RAM_stockid], "Output/total.land.latbin.stock.rds")
